name: Build

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 构建和发布 Electron 应用
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: 检出 Git 仓库
        uses: actions/checkout@v3.0.0

      - name: 安装 Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '18.14.0' # 将 Node.js 版本更改为适用的版本

      - name: 安装依赖
        run: npm install

      - name: 清理平台的构建产物
        run: |
          npx rimraf "dist/**"

      - name: 构建 Electron 应用
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: dist

      - name: 发布 Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'dist/**'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
